export const SCHOOL_STREAMS = [
  'Play Group Mourine',
  'Play Group Gachira',
  'Play Group Salome',
  'PP1 Munene',
  'PP1 Ann',
  'PP1 Fresha',
  'PP2 Carol',
  'PP2 Mary',
  'PP2 Triza',
  'Grade 1 East',
  'Grade 1 West',
  'Grade 1 North',
  'Grade 2 East',
  'Grade 2 West',
  'Grade 2 North',
  'Grade 3 East',
  'Grade 3 West',
  'Grade 3 North',
  'Grade 4 East',
  'Grade 4 West',
  'Grade 4 North',
  'Grade 4 South',
  'Grade 5 East',
  'Grade 5 West',
  'Grade 5 North',
  'Grade 5 South',
  'Grade 6 East',
  'Grade 6 West',
  'Grade 6 North',
  'Grade 7 Batian',
  'Grade 7 Lenana',
  'Grade 7 Nelion',
  'Grade 8 Lenana',
  'Grade 8 Batian',
  'Grade 9 Lenana',
  'Grade 9 Batian'
];
